package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

// The ForceNew index as a file.
//
// Extraction and pack generation used to be two halves of one process, with the
// index living only in memory between them. Writing it out costs nothing and
// buys three things the in-memory version cannot have:
//
//   - It can be reviewed. The index is the output of reading someone else's Go
//     source heuristically; "which arguments did we decide are ForceNew" is a
//     question worth being able to answer without a debugger.
//   - It can be diffed between provider releases. A release that silently drops
//     ForceNew coverage for a service package currently looks identical to one
//     that changes nothing.
//   - It can be a test fixture. The merge onto the attribute surface, the
//     validity filter, and the pack layout are all testable against a small
//     committed index instead of a multi-gigabyte provider checkout.
//
// It is also the seam the Python port consumes: the extractor stays here,
// because the language it reads is Go and Go ships the only authoritative
// parser for it, while everything downstream of the index is generated by
// tfpdf-genpack. Nothing about the format is Python-specific.
type forceNewIndexFile struct {
	Provider        string `json:"provider"`
	ProviderVersion string `json:"provider_version"`

	// TopLevel maps resource type -> ForceNew top-level argument names.
	TopLevel map[string][]string `json:"top_level"`
	// Nested maps resource type -> dotted block path -> ForceNew names.
	Nested map[string]map[string][]string `json:"nested"`

	Stats forceNewIndexStats `json:"stats"`
}

type forceNewIndexStats struct {
	SDKResourcesSeen     int `json:"sdk_resources_seen"`
	SDKResourcesResolved int `json:"sdk_resources_resolved"`
	FrameworkSeen        int `json:"framework_seen"`
	FrameworkResolved    int `json:"framework_resolved"`
}

// writeForceNewIndex serialises an index. Lists are sorted so that re-running
// the extractor over an unchanged provider checkout produces an identical
// file — the same reason Pack.sortAll exists.
func writeForceNewIndex(path, provider, providerVer string, idx *forceNewIndex) error {
	out := forceNewIndexFile{
		Provider:        provider,
		ProviderVersion: providerVer,
		TopLevel:        map[string][]string{},
		Nested:          map[string]map[string][]string{},
		Stats: forceNewIndexStats{
			SDKResourcesSeen:     idx.SDKResourcesSeen,
			SDKResourcesResolved: idx.SDKResourcesResolved,
			FrameworkSeen:        idx.FrameworkSeen,
			FrameworkResolved:    idx.FrameworkResolved,
		},
	}

	for rType, attrs := range idx.TopLevel {
		v := dedupe(append([]string(nil), attrs...))
		sort.Strings(v)
		out.TopLevel[rType] = v
	}
	for rType, byPath := range idx.Nested {
		m := map[string][]string{}
		for path, attrs := range byPath {
			v := dedupe(append([]string(nil), attrs...))
			sort.Strings(v)
			m[path] = v
		}
		out.Nested[rType] = m
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(out); err != nil {
		return fmt.Errorf("encoding ForceNew index: %w", err)
	}
	return f.Close()
}

// extractorFor returns the ForceNew extractor for a provider. The walker
// underneath is shared; what differs is how a resource type string is matched
// to its schema function.
func extractorFor(provider string) func(string) (*forceNewIndex, error) {
	if provider == "azurerm" {
		return extractForceNewAzurerm
	}
	return extractForceNew
}

// dedupe retire les doublons en préservant l'ordre. Copié depuis
// schemajson.go de genpack, qui reste dans l'arbre Go : c'est douze lignes,
// et les importer aurait voulu dire faire dépendre cet outil du module même
// dont on le détache.
func dedupe(in []string) []string {
	seen := make(map[string]bool, len(in))
	out := in[:0]
	for _, v := range in {
		if seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	return out
}
