"""Test actual cloud-name resolution. Empty means unknown, never confirmed absence; querying AWS
with an invented name could incorrectly lower severity.
"""

from __future__ import annotations

import pytest

from tfpdf import cloudname
from tfpdf.diff import ChangedFile
from tfpdf.parser import parse_file
from tfpdf.report.finding import Severity
from tfpdf.rules import RunOptions, default_rules, run
from tfpdf.schema import KnowledgeBase
from tfpdf.schema import load as load_schema


def _resource(source: bytes, name: str = "a"):  # type: ignore[no-untyped-def]
    return next(r for r in parse_file("t.tf", source) if r.name == name)


def test_the_naming_attribute_is_not_called_name_on_every_type() -> None:
    """Different resource types use different cloud-name attributes."""
    cases = [
        (b'resource "aws_s3_bucket" "a" { bucket = "prod-backups" }', "prod-backups"),
        (b'resource "aws_db_instance" "a" { identifier = "prod-db" }', "prod-db"),
        (b'resource "aws_lambda_function" "a" { function_name = "resize" }', "resize"),
    ]
    for source, expected in cases:
        assert cloudname.of(_resource(source)) == expected


def test_the_name_attribute_of_a_database_is_not_its_identifier() -> None:
    """A database's name identifies the database inside the instance, not the instance itself; do
    not use it as an identifier fallback.
    """
    resource = _resource(b'resource "aws_db_instance" "a" { name = "appdb" }')
    assert cloudname.of(resource) == ""


def test_a_type_the_table_does_not_cover_says_so() -> None:
    resource = _resource(b'resource "aws_quantum_widget" "a" { name = "w" }')
    assert cloudname.of(resource) == ""


def test_a_name_built_at_apply_time_is_not_a_name() -> None:
    """An unresolved variable is not a usable cloud name."""
    resource = _resource(b'resource "aws_s3_bucket" "a" { bucket = var.bucket_name }')
    assert cloudname.of(resource) == ""


def test_an_interpolated_name_is_not_a_name() -> None:
    resource = _resource(b'resource "aws_s3_bucket" "a" { bucket = "pre-${var.env}" }')
    assert cloudname.of(resource) == ""


def test_a_missing_attribute_is_not_a_name() -> None:
    """An omitted bucket name is generated by the provider and cannot be inferred here."""
    resource = _resource(b'resource "aws_s3_bucket" "a" { force_destroy = true }')
    assert cloudname.of(resource) == ""


def test_a_data_source_has_no_name_to_give() -> None:
    """Data-source reads do not represent resources created by this change."""
    resource = _resource(b'data "aws_s3_bucket" "a" { bucket = "prod-backups" }')
    assert cloudname.of(resource) == ""


def test_every_entry_in_the_table_names_a_plausible_attribute() -> None:
    """Reject malformed entries in the resource-name mapping."""
    for resource_type, attribute in cloudname.NAME_ATTRIBUTE_BY_TYPE.items():
        assert "_" in resource_type, resource_type
        assert attribute and attribute.islower(), (resource_type, attribute)


# End-to-end cloud-name checks.


@pytest.fixture(scope="module")
def kb() -> KnowledgeBase:
    return load_schema()


def test_a_finding_carries_both_the_address_and_the_real_name(kb: KnowledgeBase) -> None:
    """Keep the Terraform address for reviewers and the actual name for provider APIs."""
    source = b"""resource "aws_s3_bucket" "backups" {
  bucket        = "prod-backups"
  force_destroy = true
}
"""
    findings = run([ChangedFile(path="s3.tf", head_content=source)], kb, default_rules()).findings
    force_destroy = next(f for f in findings if f.rule_name == "s3_force_destroy")

    assert force_destroy.resource == "aws_s3_bucket.backups"
    assert force_destroy.cloud_name == "prod-backups"


def test_the_severity_check_is_not_called_without_the_opt_in(
    kb: KnowledgeBase, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Without cloud-read opt-in, do not run cloud severity checks."""
    import botocore.client

    calls: list[str] = []
    monkeypatch.setattr(
        botocore.client.BaseClient,
        "_make_api_call",
        lambda self, name, params: calls.append(name),
    )
    source = b"""resource "aws_s3_bucket" "backups" {
  bucket        = "prod-backups"
  force_destroy = true
}
"""
    result = run([ChangedFile(path="s3.tf", head_content=source)], kb, default_rules())

    assert calls == []
    assert (
        next(f for f in result.findings if f.rule_name == "s3_force_destroy").severity
        is Severity.MEDIUM
    )


def test_with_the_opt_in_the_check_receives_the_real_bucket_name(
    kb: KnowledgeBase, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Pass the actual bucket name rather than its Terraform address to S3."""
    received: list[str] = []

    def check(severity: Severity, bucket: str) -> str:
        received.append(bucket)
        return "critical"

    # Mock access so the test never depends on the developer's AWS credentials.
    monkeypatch.setattr("tfpdf.ruledef.severitycheck.available_context", lambda: True)
    monkeypatch.setattr("tfpdf.ruledef.severitycheck.s3_force_destroy_severity_check", check)
    source = b"""resource "aws_s3_bucket" "backups" {
  bucket        = "prod-backups"
  force_destroy = true
}
"""
    result = run(
        [ChangedFile(path="s3.tf", head_content=source)],
        kb,
        default_rules(),
        RunOptions(cloud_reader=object()),
    )

    assert received == ["prod-backups"]
    finding = next(f for f in result.findings if f.rule_name == "s3_force_destroy")
    # The checker returns a string; the finding field must remain a Severity.
    assert finding.severity is Severity.CRITICAL


def test_a_bucket_whose_name_is_a_variable_is_never_looked_up(
    kb: KnowledgeBase, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Never query a bucket whose name cannot be resolved."""
    called: list[str] = []
    # Mock successful access so an unknown name, not a failed probe, explains the skipped
    # lookup.
    monkeypatch.setattr("tfpdf.ruledef.severitycheck.available_context", lambda: True)
    monkeypatch.setattr(
        "tfpdf.ruledef.severitycheck.s3_force_destroy_severity_check",
        lambda severity, bucket: called.append(bucket) or "low",
    )
    source = b"""resource "aws_s3_bucket" "backups" {
  bucket        = var.bucket_name
  force_destroy = true
}
"""
    result = run(
        [ChangedFile(path="s3.tf", head_content=source)],
        kb,
        default_rules(),
        RunOptions(cloud_reader=object()),
    )

    assert called == []
    assert (
        next(f for f in result.findings if f.rule_name == "s3_force_destroy").severity
        is Severity.MEDIUM
    )


# One probe per scan.


THREE_BUCKETS = b"""resource "aws_s3_bucket" "one" {
  bucket        = "bucket-one"
  force_destroy = true
}

resource "aws_s3_bucket" "two" {
  bucket        = "bucket-two"
  force_destroy = true
}

resource "aws_s3_bucket" "three" {
  bucket        = "bucket-three"
  force_destroy = true
}
"""


def test_the_account_is_probed_once_however_many_buckets_there_are(
    kb: KnowledgeBase, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Probe STS and initialize the client once per scan, not once per finding."""
    probes: list[int] = []
    checked: list[str] = []
    monkeypatch.setattr(
        "tfpdf.ruledef.severitycheck.available_context",
        lambda: probes.append(1) or True,
    )
    monkeypatch.setattr(
        "tfpdf.ruledef.severitycheck.s3_force_destroy_severity_check",
        lambda severity, bucket: checked.append(bucket) or "critical",
    )

    run(
        [ChangedFile(path="s3.tf", head_content=THREE_BUCKETS)],
        kb,
        default_rules(),
        RunOptions(cloud_reader=object()),
    )

    assert checked == ["bucket-one", "bucket-two", "bucket-three"]
    assert len(probes) == 1


def test_nothing_to_corroborate_means_no_probe_at_all(
    kb: KnowledgeBase, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Even with opt-in, skip AWS when there is no eligible finding."""
    probes: list[int] = []
    monkeypatch.setattr(
        "tfpdf.ruledef.severitycheck.available_context",
        lambda: probes.append(1) or True,
    )
    source = b"""resource "aws_s3_bucket" "quiet" {
  bucket = "nothing-to-see"
}
"""
    run(
        [ChangedFile(path="s3.tf", head_content=source)],
        kb,
        default_rules(),
        RunOptions(cloud_reader=object()),
    )

    assert probes == []


def test_a_context_that_cannot_be_opened_stops_before_the_checks(
    kb: KnowledgeBase, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Failed access must preserve static severities and skip checks."""
    checked: list[str] = []
    monkeypatch.setattr("tfpdf.ruledef.severitycheck.available_context", lambda: False)
    monkeypatch.setattr(
        "tfpdf.ruledef.severitycheck.s3_force_destroy_severity_check",
        lambda severity, bucket: checked.append(bucket) or "low",
    )

    result = run(
        [ChangedFile(path="s3.tf", head_content=THREE_BUCKETS)],
        kb,
        default_rules(),
        RunOptions(cloud_reader=object()),
    )

    assert checked == []
    assert all(
        f.severity is Severity.MEDIUM for f in result.findings if f.rule_name == "s3_force_destroy"
    )


def test_the_check_itself_never_probes(kb: KnowledgeBase) -> None:
    """Individual severity checks must reuse the engine's cached access result."""
    import ast
    import inspect
    import textwrap

    from tfpdf.ruledef import severitycheck

    # Inspect the AST so comments mentioning the function do not count as calls.
    tree = ast.parse(
        textwrap.dedent(inspect.getsource(severitycheck.s3_force_destroy_severity_check))
    )
    called = {
        node.func.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
    }
    assert "available_context" not in called
